name: Auto-Format Python Code with Black

on:
  push:  
  pull_request:  

jobs:
  format-python:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 🔄 Format only changed Python files
        run: |
          export PYTHONPATH=$PWD/tools/python  # Use the new Python-specific path
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- '*.py')

          if [[ -z "$CHANGED_FILES" ]]; then
            echo "⚠️ No changed Python files found. Skipping formatting."
            exit 0
          fi

          echo "📂 Changed Python files detected:"
          echo "$CHANGED_FILES"

          for file in $CHANGED_FILES; do
            echo "⚡ Formatting $file..."
            python tools/python/bin/black "$file"
          done

      - name: 🚀 Commit formatted Python files
        run: |
          export PYTHONPATH=$PWD/tools/python  # Use the new Python-specific path
          CHANGED_FILES=$(git diff --name-only -- '*.py')

          if [[ -z "$CHANGED_FILES" ]]; then
            echo "⚠️ No formatting changes detected. Skipping commit."
            exit 0
          fi

          echo "🔄 Adding formatted Python files..."
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          for file in $CHANGED_FILES; do
            git add "$file"
          done

          git commit -m "[CI_SKIP] 🔄 Auto-formatted Python files" || echo "⚠️ No changes to commit"
          git push || echo "⚠️ No changes to push"